/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.funczz.gradle.plugin.payara_micro

import io.kotlintest.matchers.string.shouldContain
import io.kotlintest.specs.StringSpec
import org.gradle.testkit.runner.GradleRunner
import java.io.File

/**
 * A simple functional test for the plugin.
 */
class PayaraMicroGradlePluginFunctionalTest : StringSpec() {

    private val kotlinPluginsBlock = """
        plugins {
            id("payara-micro-gradle-plugin")
        }
        """.trimIndent()

    init {

        "can run task using Kotlin-DSL" {
            // Setup the test build
            val projectDir = File("build/functionalTest")
            projectDir.mkdirs()
            projectDir.resolve("settings.gradle.kts").writeText("")
            projectDir.resolve("build.gradle.kts").writeText(kotlinPluginsBlock)

            // Run the build
            val runner = GradleRunner.create().apply {
                withProjectDir(projectDir)
                withPluginClasspath()
                withDebug(true)
                forwardOutput()
                withArguments("example")
            }
            val result = runner.build()

            // Verify the result
            result.output shouldContain "hello world."
        }
    }
}
