/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.funczz.gradle.plugin.payara_micro

import io.kotlintest.matchers.string.shouldContain
import io.kotlintest.specs.StringSpec
import org.gradle.testkit.runner.GradleRunner
import java.io.File

/**
 * A simple functional test for the plugin.
 */
class PayaraMicroGradlePluginFunctionalTest : StringSpec() {

    private val kotlinPluginsBlock = """
        plugins {
            id("payara-micro-gradle-plugin")
            id("java")
        }
        repositories {
            mavenLocal()
            mavenCentral()
        }
        dependencies {
            testRuntimeOnly("fish.payara.extras:payara-micro:5.2021.1")
        }
        """.trimIndent()

    init {

        "can run task using Kotlin-DSL" {
            // Setup the test build
            val projectDir = File("build/functionalTest")
            projectDir.mkdirs()
            projectDir.resolve("settings.gradle.kts").writeText("")
            projectDir.resolve("build.gradle.kts").writeText(kotlinPluginsBlock)

            // Run the build
            val runner = GradleRunner.create().apply {
                withProjectDir(projectDir)
                withPluginClasspath()
                withDebug(true)
                forwardOutput()
                withArguments("payaraVersion")
            }
            val result = runner.build()

            // Verify the result
            result.output shouldContain "Payara Micro "
        }
    }
}
