/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.funczz.gradle.plugin.payara_micro

import org.gradle.api.Plugin
import org.gradle.api.Project

/**
 * Plugin
 */
class PayaraMicroGradlePlugin : Plugin<Project> {

    override fun apply(project: Project) {

        val extension = project.extensions.create("PayaraMicroGradlePluginExtension", PayaraMicroGradlePluginExtension::class.java)

        project.tasks.register("example") { task ->
            task.apply {
                group = "example plugin"
                //dependsOn("war")

                doFirst {
                }
                doLast {
                    val result = when(extension.value.isBlank()) {
                        true -> "hello world."
                        else -> extension.value
                    }
                    println(result)
                }
            }
        }

    }
}
