/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.funczz.gradle.plugin.payara_micro

import io.kotlintest.shouldBe
import io.kotlintest.specs.StringSpec
import org.gradle.testfixtures.ProjectBuilder

class PayaraMicroGradlePluginTest : StringSpec() {

    init {

        "plugin registers task" {
            // Create a test project and apply the plugin
            val project = ProjectBuilder.builder().build()
            project.plugins.apply("payara-micro-gradle-plugin")

            // Verify the result
            project.tasks.findByName("example").toString() shouldBe "task ':example'"
        }
    }

}
