name: test

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  test:
    name: Test on JDK8
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
          cache: gradle
      - name: Test with Gradle
        run: ./gradlew test
